logging:
  level:
    root: INFO
    org.springframework: DEBUG
#    org.springframework.boot.autoconfigure.security: INFO
#    org.springframework.security: INFO
#    org.springframework.web: INFO
spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          halt_on_error: true
        show_sql: true
        format_sql: false
        use_sql_comments: false
